; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = Firmware para Dashboard (ESP32-C3)
description = Firmware para o dashboard com ESP32-C3, contém o painel do Gol G6, um display TFT e um display OLED.
default_envs =
  ; rpipico2
  ; super_mini_esp32c3
  ; test_oled
  test_tft
build_cache_dir = .pio/buildcache
boards_dir = boards/json
cache_dir = .pio/cache
platforms_dir = .pio/platforms
packages_dir = .pio/packages

extra_configs =
	boards/*.ini
	boards/*/*.ini

[env]
framework = arduino
build_type = release
build_flags =
  -Wall
  ; -Werror
check_tool = cppcheck, clangtidy
check_skip_packages = yes

build_src_filter =
  +<**/*.cpp>
  +<**/*.h>
  -<tests/**>

; ========= TESTE OLED =========
[env:test_oled]
extends = env:super_mini_esp32c3
lib_deps =
  olikraus/U8g2 @ ^2.36.17
build_src_filter =
  +<**/*.cpp>
  +<**/*.h>
  -<main.cpp>
  -<tests/**>
  +<tests/main_oled.cpp>

; ========= TESTE TFT =========
[env:test_tft]
extends = env:rpipico2
lib_deps =
  bodmer/TJpg_Decoder @ ^1.1.0
  bodmer/TFT_eSPI @ ^2.5.43
build_src_filter =
  +<**/*.cpp>
  +<**/*.h>
  -<main.cpp>
  -<tests/**>
  +<tests/main_tft.cpp>
